# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 270f907eda40c6b3705b7bd560cd07734a7c6e9e72313225aec2d3966b07b0fb3300ddb1deb89468cad037a481183cc906972a0efe5fc3d695688902522dfda3

test:
  secret_key_base: 1de56bae295ab019163fe8383edf268c9336da27518a61ad0fc3161e2db87c74eff4c894a8a1d446fac233da757395579ed606e6dcd6394d4dab4d2c1602d398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
